Query multiple tables
clin2on3mun/VetClinic-database pull request #3
Opened 2023-07-12 20:09 UTC by clin2on3mun

in this milestone:
-created owners table
- created species table
Action done to tables
created owner table with data
![owner's table](https://github.com/clin2on3mun/VetClinic-database/assets/95659892/0f8e9982-ef38-4a56-8788-72ddff73cea1)
created species and add data
![species table](https://github.com/clin2on3mun/VetClinic-database/assets/95659892/69bd59d9-6a84-45c5-adee-27872c47e27c)
Remove species column in animal table

![removeSpeciescOLUMN](https://github.com/clin2on3mun/VetClinic-database/assets/95659892/0d8a9842-b937-4830-bb61-e12e188eb442)

using foreign key to reference table 

![query-multiple -tables](https://github.com/clin2on3mun/VetClinic-database/assets/95659892/bee81c3c-d7ad-44a2-bf32-f2973ae1aad0)

2023-07-12 23:23 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @clin2on3mun , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media3.giphy.com/media/W0c3xcZ3F1d0EYYb0f/giphy.gif"/> |

## Highlights

- [ ].. ✅ SQL queries
- [ ].. ✅ Readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 23:23 UTC, joskalenda commented on README.md
- [ ] Please make sure you create a MIT.md file in your app directory and customize its content, then take care of updating your readme mit file link as for now it is redirecting the user to another page

2023-07-13 06:38 UTC, clin2on3mun commented on README.md
HI @joskalenda 
I am not getting changes i will make

2023-07-13 06:42 UTC, binhussen approved these changes
Hi @clin2on3mun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
![AgreeSealGIF](https://github.com/clin2on3mun/VetClinic-database/assets/52010789/3e4b1673-2654-4fe2-9a98-090de1f86a5c)

## Highlights
- Well Structured Query ✔️
- Descriptive pull request with screenshot ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 06:49 UTC, merged